- name: Copy vivpilights service to systemd folder
  become: true
  copy:
    src: "files/vivpilights.service"
    dest: "/etc/systemd/system/vivpilights.service"

- name: Copy vivpilights timer to systemd folder
  become: true
  copy:
    src: "files/vivpilights.timer"
    dest: "/etc/systemd/system/vivpilights.timer"

- name: Configure vivpi install location
  become: true
  replace:
    path: "/etc/systemd/system/vivpilights.service"
    regexp: '(install_location)'
    replace: "{{ install_location }}"

- name: Enable vivpilights service
  become: true
  service:
    name: vivpilights.service
    enabled: yes
    state: stopped

- name: Enable vivpilights timer 
  become: true
  service:
    name: vivpilights.timer
    enabled: yes
    state: stopped