- name: Copy vivpi service to systemd folder
  become: true
  copy:
    src: "files/vivpi.service"
    dest: "/etc/systemd/system/vivpi.service"

- name: Copy vivpi timer to systemd folder
  become: true
  copy:
    src: "files/vivpi.timer"
    dest: "/etc/systemd/system/vivpi.timer"

- name: Configure vivpi install location
  become: true
  replace:
    path: "/etc/systemd/system/vivpi.service"
    regexp: '(install_location)'
    replace: "{{ install_location }}"

- name: Enable vivpi service
  become: true
  service:
    name: vivpi.service
    enabled: yes
    state: stopped

- name: Enable vivpi timer 
  become: true
  service:
    name: vivpi.timer
    enabled: yes
    state: stopped